### ISSUE TITLE
Variable Variable prohibition in strict mode causes failures where it should not (as late as release 2.1.1)

### ISSUE THREAD

**Issue by vctrshn** [box/brainy#12]
{for $i=0 to $foo.bar.baz-1}
{for $i=0 to count($foo)-1}
{for $i=0 to count($foo)-1 step 2}
{for $i=1 to $foo}
{for $i=count($foo)-1 to 0 step -1}
{for $i=0 to 5 step 2}

**Comment by mattbasta** [comment]
Needs to be back-ported to 2.1.x

**Comment by mattbasta** [comment]
Fixed in 2.1.3
