### ISSUE TITLE
Ternary operator pls

### ISSUE THREAD

**Issue by knewkirk** [box/brainy#24]
It would be really darn cool if the ternary operator was a thing.

Right now:

```
{if $condition} 
    {$var = $true_option}   
{else}  
    {$var = $false_option}  
{/if}
```

Super premium:
`{$var = $condition ? $true_option : $false_option}`

**Comment by mattbasta** [comment]
It already exists, but it might not be available for shorthand assignments.

https://github.com/box/brainy/blob/master/build/parsers/Parser.y#L674

**Comment by mattbasta** [comment]
Ah, it looks like you have to put parens around your expression:

``` smarty
{$var = ($condition) ? $true_cond : $false_cond}
```

**Comment by mattbasta** [comment]
Looks like there's tests, as well. RESOLVED: ALREADY FIXED! :dancer: 

https://github.com/box/brainy/blob/master/test/TernaryTest.php

**Comment by knewkirk** [comment]
Sweet thanks for investigating!
