### ISSUE TITLE
Contributor permissions

### ISSUE THREAD

**Issue by mattbasta** [box/brainy#25]
It would be nice to have contributor permissions again. After all, I've got the most knowledge around how the code works and how it's used in practice.

<img width="472" alt="screen shot 2016-04-07 at 12 21 24 pm" src="https://cloud.githubusercontent.com/assets/279498/14363910/562420a2-fcbb-11e5-8581-aa0d717ec6d7.png">

**Comment by vctrshn** [comment]
Just added you as a collaborator!
